### ISSUE TITLE
Propagate error status for retriable errors

### ISSUE THREAD

**Issue by nilebox** [atlassian/smith#318] opened 2018-09-19 04:17 UTC
When Service Catalog reports status with a temporary error, it doesn't set the `Failure` condition. It has only `Ready` condition with `status: False` and reason/message describing a temporary error.
Example:
```yaml
  conditions:
  - lastTransitionTime: 2018-09-19T03:25:56Z
    message: 'Error provisioning ServiceInstance of ClusterServiceClass (K8S: "<redacted>"
      ExternalName: "sqs") at ClusterServiceBroker "aws-broker": Status: 409; ErrorMessage:
      <nil>; Description: Service instance with the given ID already exists: serviceInstanceId=<redacted>,
      serviceDefinitionId=<redacted>; ResponseError: <nil>'
    reason: ProvisionCallFailed
    status: "False"
    type: Ready
```

When Smith is processing such status, it simply reports with "InProgress: True" and no additional message/reason, e.g.
```
    - conditions:
      - lastTransitionTime: 2018-09-19T03:19:58Z
        lastUpdateTime: null
        status: "False"
        type: Blocked
      - lastTransitionTime: 2018-09-19T03:19:58Z
        lastUpdateTime: null
        status: "True"
        type: InProgress
      - lastTransitionTime: 2018-09-19T03:19:58Z
        lastUpdateTime: null
        status: "False"
        type: Ready
      - lastTransitionTime: 2018-09-19T03:19:58Z
        lastUpdateTime: null
        status: "False"
        type: Error
      name: perftest-queue--instance
```

**Comment by ash2k** [comment] 2018-09-28 12:40
@benbarclay another issues that is almost a duplicate of this one is https://github.com/atlassian/smith/issues/317. That one is about propagating "in progress" while this one is about error conditions. Feel free to solve both in a single PR 🤷‍♂️

**Closed** 2018-10-15 02:19 UTC
Labels: bug
